# Generated by Django 4.2.27 on 2026-01-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight in Kg')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.scrapcategory')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pickuprequest')),
            ],
        ),
    ]
