# Generated by Django 5.2.10 on 2026-01-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pickupitem'),
        ('core', '0002_pickuprequest_scrap_category'),
    ]

    operations = [
    ]
