# Generated by Django 4.2.27 on 2026-01-29 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.CreateModel(
            name='PickupStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text="Short status, e.g., 'On the way'", max_length=100)),
                ('location', models.CharField(help_text="Current location, e.g., 'Surat'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional details', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='core.pickuprequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
