# Generated by Django 4.2.27 on 2026-02-05 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_latitude_remove_user_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
