# Generated by Django 4.2.27 on 2026-02-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pickuprequest_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
